title: Husayn El Sharif, PhD
#logo: /assests/img/headshot_circle.png
#description: Data Science Portfolio
# to allow downloads, set show_downloads to true
show_downloads: true
theme: jekyll-theme-minimal
